#!/bin/bash

docker run \
    -it \
    --rm \
    -p 8000:8000 \
    --link influxdb:database \
    -e ROCKET_ADDRESS=0.0.0.0 \
    -e ROCKET_ENV=dev \
    -e DB_HOST_ADDR=http://database:8086 \
    --name wds \
    wifind/datastore
